- assets/css/common/base.scss
- assets/js/interactions.js
- lib/philomena_web/templates/image/show.html.slime
- lib/philomena_web/templates/layout/_opengraph.html.slime
- lib/philomena_web/templates/registration/totp/edit.html.slime
Command used:
codespell -wi3 **/* --ignore-words-list "dur,fave,fo,receipient,te"
> Fix various typos using `codespell`

- priv/repo/seeds.exs
- priv/repo/seeds_development.exs
When setting (resetting) up an environment, the roles were not being applied. This fixes that (thanks to byte for telling me how to fix it)
> Fix for roles not being applied to default users

- lib/philomena_web/controllers/conversation_controller.ex
Implements the logic necessary to make the "Our Conversations" link on profiles work.
> Add query to enable 'our conversations' functionality

- lib/philomena_web/controllers/api/json/tag_controller.ex
---
This stops a bug I noticed when a slug that doesn't match is given. This will correctly 404 rather than redirecting to front page.
> Corrects failure and redirect to main page

- lib/philomena_web/comment_json.ex
- lib/philomena_web/controllers/api/json/comment_controller.ex
- lib/philomena_web/router.ex
---
Adds a new endpoint `/api/v1/json/comment/:id`.
Mostly working on getting the hang of adding new ones, and figured I might as well commit my test one.
> Adding /api/v1/json/comment/:id endpoint

- lib/philomena_web/controllers/api/json/forum/topic/post_controller.ex
- lib/philomena_web/controllers/api/json/forum/topic_controller.ex
- lib/philomena_web/router.ex
---
Fix to the module locations for the ones I added previously. Also a fix for when a forum topic gives a page with no results.
> Somewhat damaged patch 1

- lib/philomena_web/award_json.ex
- lib/philomena_web/controllers/api/json/profile_controller.ex
- lib/philomena_web/links_json.ex
- lib/philomena_web/router.ex
- lib/philomena_web/user_json.ex
---
Adds the '/api/v1/json/profiles/:id` endpoint to the API.
> This will add the  endpoint to the API.

- lib/philomena_web/controllers/api/json/filter_controller.ex
- lib/philomena_web/filter_json.ex
- lib/philomena_web/router.ex
---
This adds a new endpoint `/filters/:id` to the JSON API.
> New /filters/:id API endpoint

- lib/philomena_web/controllers/api/json/forum/topic/post_controller.ex
- lib/philomena_web/controllers/api/json/forum/topic_controller.ex
- lib/philomena_web/controllers/api/json/forums_controller.ex
---
Cleaning up endpoints I'd made now I know how to do things properly.
> Adjusted to suit standard

- lib/philomena_web/controllers/api/json/image/featured_controller.ex
- lib/philomena_web/controllers/api/json/image_controller.ex
- lib/philomena_web/controllers/api/json/search/image_controller.ex
- lib/philomena_web/controllers/api/json/search/reverse_controller.ex
- lib/philomena_web/views/api/json/image_view.ex
Changes ImageJson to a Phoenix view. Requesting review to make sure I didn't accidentally introduce a breaking change to the API.
> Change ImageJson to view

- lib/philomena_web/controllers/api/json/image/featured_controller.ex
- lib/philomena_web/controllers/api/json/image_controller.ex
- lib/philomena_web/views/api/json/image_view.ex
---
Adds interactions to `/api/v1/json/images/:id` and `/api/v1/json/images/featured`
> API additions for user interactions on single images

- lib/philomena/dnp_entries/dnp_entry.ex
- [x ] I understand all of the above
---
Reduce code duplication and lessen potential for future changes to break functionality
> Derive DNP types from reasons

- lib/philomena_web/plugs/pow_invalidated_session_plug.ex
Fixes issue introduced with #36 
~~I'll work a bit further with this to prevent issues with the TOTP plug, and then it should be ready.~~ Scratch that, it's an edge case there is no need to handle since we don't want such actions to happen outside the valid session.
> Fix plug issue

- lib/philomena_web/plugs/pow_invalidated_session_plug.ex
- test/philomena_web/plug/pow_invalidated_session_plug_test.exs
This stores the TOTP metadata so TOTP authed sessions will still work.
> Add TOTP support in the invalidation session plug

- assets/js/boorujs.js
> Poll tabs bug

- lib/philomena_web/templates/profile/_about_me.html.slime
> Fix broken link in profile about me box (closes #131)

- assets/js/upload.js
> Fixes #134

- assets/js/.eslintignore
- assets/js/.eslintrc.yml
- assets/js/upload.js
---
Added the js linting config files from the old repo
> Js linting rules

- lib/philomena_web/templates/avatar/edit.html.slime
- lib/philomena_web/templates/profile/show.html.slime
> Link avatar on users own profile to the avatar change page

- lib/philomena/users/ability.ex
- lib/philomena_web/controllers/profile/commission_controller.ex
> Allow moderators to edit commissions

- lib/philomena_web/controllers/comment_controller.ex
- lib/philomena_web/controllers/post_controller.ex
> assistants can now see deleteds in comments/forum search

- config/quick_tag_table.json
Removes old spoilers
Adds student six
Fixed an episode tag that was wrong
> Quick tags table update

- lib/philomena_web/templates/layout/_burger.html.slime
---
https://github.com/derpibooru/philomena/commit/47ab6ed83b89404577d1873af069d7e99ebbc43b#diff-50e8bcb87a91918b7962c1ed48b302f6d0cb0f529833c7428ad6d9e5f142e8f7R16
> Fix trending search query in mobile layout
