derpibooru/philomena

lib/philomena_web/controllers/staff_controller.ex

The secondary_role field is pretty entirely cosmetic and is not referenced anywhere other than in staff nametags (user_attribution_view.ex) and the staff directory page itself. Historically it's only been used for site developers, and thus if it was present at all it'd list anyone with it under "Technical Team", but this basically splits it up based on the value so that there can be a Technical Team, a PR Team, and any other team we may need in the future.

Add PR Secondary Role to staff page

---

lib/philomena_web/templates/layout/_opengraph.html.slime

This uses `Router.image_url`, which produces the `/images/:id` route. I wasn't sure how to produce the `/:id` route, however considering gallery pages also link to `/images/:id`, perhaps this is the correct move anyway.

Add canonical link for search engine deduplication

---

lib/philomena/images/elasticsearch_index.ex

If an image's `upvotes` are 0, their Wilson score will be so minuscule as to be several (around 12) orders of magnitude before you see anything but zeros (assuming 0 `upvotes` and 1 `downvotes`). This will simply remove the calculation from such and make them fall to the default: 0

Update to streamline Wilson score generation

---

lib/fast_textile/parser.ex

- [*] I understand all of the above
---
Sets the correct `class` for hiding images.

Fix for full image spoiling

---

lib/philomena_web/controllers/tag_controller.ex
lib/philomena_web/templates/layout/_header.html.slime

---
1. This removes the `_utf-8` parameter from the URL returned when a search is made from the search bar.
2. This also removes the TeX-style quoting that was visible in the message displayed when going to a tag page for an aliased tag, e.g. [spoiler:s06e10](https://derpibooru.org/tags/spoiler-colon-s06e10) → [applejack's "day" off](https://derpibooru.org/tags/applejack%2527s%2B%2522day%2522%2Boff).

Don't put UTF-8 in search URL

---

lib/philomena_web/controllers/api/json/search/reverse_controller.ex

---
Fixes the `distance` to search not being passed through to `ImageReverse.images()`
`set_scraper_cache` passes the `distance` through into `params`
`create` normalizes and inserts the result into the params passed to `ImageReverse.images()`
`normalize_dist` checks if there is a `distance` set, adds a leading 0 to it (to account for values like `.5`, which would crash `Float.parse()`), and turns it back into a well-formatted string for `ImageReverse.images()`
This also changes the `image[distance]` value to just being `distance` instead.

Fix for distance

---

lib/philomena_web/image_loader.ex

---
This used to be allowed in the old searching with the `deleted` param for all users.
This should correctly add back the ability (using the new `del` param) to specify `del=1` for any user/API search, but correctly block them from doing the more specialized "staff only" searching.

Fix to allow users to include deleted images again

---

lib/philomena_web/controllers/activity_controller.ex

---
This makes sure the Featured Image on the front page obeys user hiding.
It correctly allows non-logged-in users to see the featured image without hindrance.
It obeys `hidden=1` special option

Featured image hiding

---

lib/philomena_web/controllers/api/json/filter/system_filter_controller.ex
lib/philomena_web/controllers/api/json/filter/user_filter_controller.ex
lib/philomena_web/controllers/api/json/filter_controller.ex
lib/philomena_web/router.ex

---
This adds a `/api/v1/json/filters` endpoint that will return `system` filters or `system` filters and `user` filters if an API key is given. Will also paginate through `user` filters using a `page` parameter.

Adds /api/v1/json/filters endpoints

---

lib/philomena_web/templates/report/new.html.slime
lib/philomena_web/templates/topic/new.html.slime

---
This adds text editing bars to `New Topic` page and adds text editing bars and previewing to `New Report` pages.

Adding text editing bars to report and new topic

---

lib/philomena_web/views/api/json/comment_view.ex

---
Fixes #66.
Getting the dev environment set up in Windows was an interesting challenge. Thank goodness for the VS Code Remoting extension. Never did get debugging working though.
All the comment views now include two new fields:
- `posted_at`, the database's `created_at` field, and
- `updated_at`, the field of the same name in the database
They're `nil`ed out on deleted images, but included in deleted comments. I wasn't sure how to hide a comment from users though, so I wasn't able to test that code path.

Add timestamps to the API's comment view

---

lib/philomena/images/image.ex
lib/philomena/mime.ex
lib/philomena/uploader.ex

Helps resolve cases like #78 earlier
Requesting testing for uploading both valid and invalid image types

image upload mime validation - shows you what it thinks the mime type is

---

assets/js/ujs.js
lib/philomena_web/plugs/captcha_plug.ex

- [ x] I understand all of the above
---
Only redirect user if failed captcha was submitted via a form post. For XHR posts, return a 300 and let the client JS reload the page to show the flash message

Properly handle failed captchas after XHR post

---

config/test.exs
lib/philomena_web/endpoint.ex
lib/philomena_web/plugs/pow_invalidated_session_plug.ex
test/philomena_web/plug/pow_invalidated_session_plug_test.exs

Exploring a potential resolution to https://github.com/danschultzer/pow/issues/356 here.
The above issue exposed a variety of issues that I've squashed in Pow. The last one I can identify is not a technical issue in Pow, rather it's UX. The problem occurs if I let the session expire, and then open a bunch of tabs at the same time. The first request will successfully use the persistent session token, while all subsequent requests will fail since they use the old cookie value. Thus I've one tab where I'm authenticated, and the rest are not.
This PR adds a plug that stores a session id or persistent session token when they are rolled. If a request is unauthenticated and a session id or persistent session token exists in the request, the token will be looked up in the invalidated session …

Add plug to handle invalidated Pow session tokens

---

.gitignore
assets/js/upload.js
lib/philomena_web/templates/avatar/edit.html.slime
lib/philomena_web/templates/image/new.html.slime
lib/philomena_web/templates/search/reverse/index.html.slime

- [✓] I understand all of the above
---
*Modified html so fetch is disabled on pageload. Javascript enables it after the user has entered some text. Re-disables it if the text goes to zero, or the image upload button has been used.

Disable image scraper fetch when there is no text

---

lib/philomena_web/templates/commission/_directory_sidebar.html.slime
lib/philomena_web/templates/profile/commission/_form.html.slime

---
The checked state of checkboxes for art categories across the commission-related pages was not persisted in the DOM between page loads. This PR aims to fix this issue in the search sidebar and listing editing form.

Persist checked state of art categories across commission pages

---

lib/philomena_web/controllers/api/json/image_controller.ex
lib/philomena_web/plugs/api_require_authorization_plug.ex
lib/philomena_web/plugs/user_attribution_plug.ex
lib/philomena_web/router.ex
lib/philomena_web/views/api/json/image_view.ex

---
Adds the `POST` method to `/api/v1/json/images` to allow for API-based creation of images.
Requires API key be used. Logs IP address. Sets fingerprint to `c415049`.
Same tag requirements as site uploading.
Description and source are optional.
Will return newly created image and a `200` on success.
Will return nothing and `401` if API key missing or invalid.
Will return nothing and `403` if IP is banned or API key exists and user is banned (as per normal banning rules, excluding `fingerprint`).
Will return errors and a `400` if image could not be created.

Api create image

---

lib/philomena_web/controllers/staff_controller.ex
lib/philomena_web/templates/admin/user/_form.html.slime

* I am definitely wearing pants
---
1) Adds "Philomena Contributor" as a selectable secondary role so that this doesn't have to be manually hacked in via psql
2) Toggles visibility on the staff list based on the hide_default_role flags - this is so that if a staff member is on break from staff duties but still need the role set (for accessing staff forums and the like), they won't appear on the staff page.

Add Philomena Contrib Sec Role, Staff Page Visibility Toggle

---

assets/css/views/_profiles.scss
lib/philomena_web/controllers/staff_controller.ex
lib/philomena_web/templates/staff/index.html.slime
lib/philomena_web/views/tag_change_view.ex

As discussed on Discord, here's what it looks like.

Hide staff tag change banner for unavailable staff, and show unavailable staff on staff page.

---

lib/philomena_proxy/scrapers.ex
lib/philomena_proxy/scrapers/bluesky.ex

---
Added a scraper for Bluesky.

Add Bluesky scraper

---

lib/philomena_web/controllers/activity_controller.ex
lib/philomena_web/templates/activity/index.html.slime

Remove 'ai composition' tagged images from showing up in Trending images
